services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchange-rate-service
    ports:
      - "8080:8080"
    env_file:
      - ./configs/.env
    environment:
      # If laucnhed from compose this is override for working db
      - POSTGRES_CONN_STRING=postgresql://postgres:postgres@postgres:5432/plata-currency-exchange?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18.6
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plata-currency-exchange
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d plata-currency-exchange"]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: